### PR TITLE
Change cli to colored output

### PR DESCRIPTION
**Pull request by sya-ri**
## Changes

Makes message output more usable and better. ~~I'd like to have the `--no-color` option, but I haven't implemented it.~~

## Test

<details>
<summary>config.toml</summary>

```toml
pack_directory="pack"
```

</details>

<details>
<summary>config_9000.toml</summary>

```toml
pack_directory="pack"

['**/*.png']
maximum_width_and_height=9000
```

</details>

And some dummy images in `assets/minecraft/textures`.

[Download as zip](https://github.com/ComunidadAylas/PackSquash/files/7903012/test.zip)

### CODE REVIEW

**Review by AlexTMjugador — CHANGES_REQUESTED** [review]
Thank you very much for the PR!! It looks well thought out 🎉

However, older Windows terminals don't support the ANSI escape codes used in the implementation, and the fact that things would look wrong on systems that are still supported by Microsoft is not a nice first impression.

I think the proper way to address these cross-compatibility concerns is to leverage the features of the `crossterm` crate, which is already being used to show a fancy title. `crossterm` supports a wide variety of terminals accross all the major operating systems.

As we've discussed on Discord, it'd be great if you could refactor this to use `crossterm` ❤️

**Comment by AlexTMjugador** [comment]
Thank you very much for your work! The colors now work fine on older Windows terminals, as expected! 🎉

However, after thinking about it quite a bit, I'm not sure we want to keep using `crossterm` with the `println` and `eprintln` macros like this.

Before calling this feature complete, it'd be necessary to implement some feature to turn colors off, as you've pointed out, because colors are only appropriate for interactive fancy terminals. The trivial way of enforcing these features would be to add checks of "are colors enabled or not?" all over the place when printing any string, but that gets ugly and error-prone quickly. `crossterm` prints colors regardless of any environment variable or setting, and it doesn't offer any API to make it do nothing when necessary.

The [`termcolor`](https://crates.io/crates/termcolor) crate has a nice automatic color mode selection feature, and is lighter and simpler. However, it doesn't offer features to set the terminal title, which is something we want. We could keep using `crossterm` for the title and colors, or reimplement what `crossterm` does to set the terminal title ourselves and use `termcolor` for the colors.

So, in any case, we would need to replace the references to the Rust built-in `println` and `eprintln` macros with calls to some other macro, function or method. This item would provide a place to put the "are colors enabled or not?" checks and the library calls to actually print the maybe nice-looking strings to the console.

Coincidentally, the functionality highlighted in the previous paragraph corresponds to what's provided by logging libraries. The standard logging library in Rust is [`log`](https://docs.rs/log/latest/log/), which is lightweight by default and so customizable. With the `log` crate, we could reduce things like:

```rust
eprintln!(
    "{}Run {} -h to see command line argument help{}",
    SetForegroundColor(Color::Red),
    env!("CARGO_BIN_NAME"),
    ResetColor
);
```

To:

```rust
error!("Run {} -h to see command line argument help", env!("CARGO_BIN_NAME"));
```

And the logger implementation in use, which we can select and configure before anything is logged, would take care of formatting the strings with colors as appropriate. In the future, this should make it easier to expand the logging features (to use syslog, for example). For now, we can just use [`env_logger`](https://docs.rs/env_logger/0.9.0/env_logger/), which uses `termcolor` under the hood.

In conclusion, I think that the best way to move forward would be to use the `log` crate, ditch `crossterm`, and replicate what it does to set the terminal title ourselves. This would also speed up compile times a bit and trim down the executable, as `crossterm` pulls some (development) dependencies that are a bit heavy, like `async-std` and the entire `tokio` runtime (again).

I'm sorry for telling you to refactor this PR to use `crossterm`, because even though it works OK right now, expanding on it to make the colors toggleable will imply discarding the bulk of its changes anyway, and I didn't realize it.

Would you like to refactor the PR, hopefully for the last time (😅), to use the `log` and `env_logger` crates instead? The idea would be to use the macros provided by `log` instead of `println` or `eprintln` to print maybe pretty messages, and set up `env_logger` such that it prints the log messages with the format you came up with. I don't think that ditching `crossterm` is in scope for this PR, though.

**Comment by sya-ri** [comment]
---



---

**Comment by AlexTMjugador** [comment]
As we've discussed over Discord, I'm very excited with your changes and I hope we can merge them soon. I've just pushed some code to master to drop the crossterm dependency as stated, and introduced some QoL changes alongside that.

If you can, assuming that the CI checks pass, it would be great to rebase this PR on top of the latest master commits and check that they work fine on macOS and Windows platforms. On Windows, it'd be interesting to test the `cmd.exe` shell, the `cmd.exe` shell in legacy mode, the Git Bash shell (which uses MinTTY), and the Windows Terminal application.

**Comment by sya-ri** [comment]
It's difficult to rebase because the changes to each other were complicated. I'm sorry for the merge commit.

**Comment by AlexTMjugador** [comment]
Okay, don't worry!

**Review by AlexTMjugador — APPROVED** [review]
The PR is now ready to be merged, after some testing on the Windows terminals mentioned in a previous comment.

**Comment by AlexTMjugador** [comment]
The changes were tested and some minor things fixed. Congratulations for your second merged PR to this repository, and thank you for your effort :heart:

**Pull request merged**
